// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgyZXpc6tFdpEzu44wZAktA-lLa9Rc8zQ',
    appId: '1:666073524338:web:405e75b2031b2ba9c9baeb',
    messagingSenderId: '666073524338',
    projectId: 'taskapp-11850',
    authDomain: 'taskapp-11850.firebaseapp.com',
    storageBucket: 'taskapp-11850.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIRbHbm_-8IruF3p9GsqKC0QKRKzJVxq0',
    appId: '1:666073524338:android:c917f1c6a280ad57c9baeb',
    messagingSenderId: '666073524338',
    projectId: 'taskapp-11850',
    storageBucket: 'taskapp-11850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCylP9dAytWojmHjLDvmGZg8FfJrXHIfgk',
    appId: '1:666073524338:ios:5fc860b5b4e5c77bc9baeb',
    messagingSenderId: '666073524338',
    projectId: 'taskapp-11850',
    storageBucket: 'taskapp-11850.appspot.com',
    iosBundleId: 'com.example.Controle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCylP9dAytWojmHjLDvmGZg8FfJrXHIfgk',
    appId: '1:666073524338:ios:c287ae5bab86e08dc9baeb',
    messagingSenderId: '666073524338',
    projectId: 'taskapp-11850',
    storageBucket: 'taskapp-11850.appspot.com',
    iosBundleId: 'com.example.Controle.RunnerTests',
  );
}
